### ISSUE TITLE
Quando selecionado, não aparece o resultado em determinadas vezes.

### ISSUE THREAD

**Issue by MisaelGuilherme** [AlyciaSilva/jokenpo#1]
O jogo está ótimo, apenas em alguns respectivos momentos que não aparece a resposta se ganhou ou perdeu quando escolhido um valor. Por exemplo: Se eu jogar varias vezes reiniciando o programa, e selecionar sempre papel, tem um momento que ele não mostra o resultado.

**Comment by AlyciaSilva** [comment]
Corrigido! Obrigada @MisaelGuilherme!!!
