### ISSUE TITLE
O código usa uma biblioteca não nativa do Python. Para rodar sem problemas, segue o comando aqui embaixo

### ISSUE THREAD

**Issue by MisaelGuilherme** [AlyciaSilva/jokenpo#2]
O código utiliza uma biblioteca não nativa do python que se trata da biblioteca emojis, para rodar no seu sistema sem dar conflito, precisa instalar a mesma pelo prompt de comando, dando o seguindo comando: ->  pip install emojis <- se for pelo windows.

**Comment by AlyciaSilva** [comment]
blz
